version: '3.4'

services:
  gameoflife.csharp.api:
    image: ${DOCKER_REGISTRY-}gameoflifecsharpapi:${IMG_TAG}
    container_name: game-of-life.csharp.api
    build:
      context: .
      dockerfile: csharp/GameOfLife.CSharp.Api/Dockerfile

  gameoflife.typescript.web:
    image: ${DOCKER_REGISTRY-}gameoflifetypescriptweb:${IMG_TAG}
    container_name: game-of-life.typescript.web
    build:
      context: .
      dockerfile: typescript/GameOfLife.TypeScript.Web/Dockerfile
    depends_on:
      - gameoflife.csharp.api